# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chartWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_chartWidget(object):
    def setupUi(self, chartWidget):
        chartWidget.setObjectName("chartWidget")
        chartWidget.resize(867, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(chartWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chartOptionsFrame = QtWidgets.QFrame(chartWidget)
        self.chartOptionsFrame.setObjectName("chartOptionsFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.chartOptionsFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.axisOptionsButton = QtWidgets.QToolButton(self.chartOptionsFrame)
        self.axisOptionsButton.setCheckable(True)
        self.axisOptionsButton.setChecked(True)
        self.axisOptionsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.axisOptionsButton.setArrowType(QtCore.Qt.UpArrow)
        self.axisOptionsButton.setObjectName("axisOptionsButton")
        self.horizontalLayout_5.addWidget(self.axisOptionsButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.legendButton = QtWidgets.QToolButton(self.chartOptionsFrame)
        self.legendButton.setCheckable(True)
        self.legendButton.setChecked(True)
        self.legendButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.legendButton.setArrowType(QtCore.Qt.UpArrow)
        self.legendButton.setObjectName("legendButton")
        self.horizontalLayout_5.addWidget(self.legendButton)
        self.verticalLayout.addWidget(self.chartOptionsFrame)
        self.axisOptionsFrame = QtWidgets.QFrame(chartWidget)
        self.axisOptionsFrame.setLineWidth(0)
        self.axisOptionsFrame.setObjectName("axisOptionsFrame")
        self.axisOptionsLayout = QtWidgets.QHBoxLayout(self.axisOptionsFrame)
        self.axisOptionsLayout.setContentsMargins(0, 0, 0, 0)
        self.axisOptionsLayout.setSpacing(0)
        self.axisOptionsLayout.setObjectName("axisOptionsLayout")
        self.verticalAxisOptionsGroupBox = QtWidgets.QGroupBox(self.axisOptionsFrame)
        self.verticalAxisOptionsGroupBox.setObjectName("verticalAxisOptionsGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.verticalAxisOptionsGroupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.normaliseDateEdit = QtWidgets.QDateEdit(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseDateEdit.sizePolicy().hasHeightForWidth())
        self.normaliseDateEdit.setSizePolicy(sizePolicy)
        self.normaliseDateEdit.setObjectName("normaliseDateEdit")
        self.gridLayout_10.addWidget(self.normaliseDateEdit, 2, 3, 1, 1)
        self.normaliseStartButton = QtWidgets.QPushButton(self.verticalAxisOptionsGroupBox)
        self.normaliseStartButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.normaliseStartButton.setObjectName("normaliseStartButton")
        self.gridLayout_10.addWidget(self.normaliseStartButton, 2, 1, 1, 1)
        self.percentageRadioButton = QtWidgets.QRadioButton(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.percentageRadioButton.sizePolicy().hasHeightForWidth())
        self.percentageRadioButton.setSizePolicy(sizePolicy)
        self.percentageRadioButton.setChecked(True)
        self.percentageRadioButton.setObjectName("percentageRadioButton")
        self.gridLayout_10.addWidget(self.percentageRadioButton, 2, 0, 1, 1)
        self.valueRadioButton = QtWidgets.QRadioButton(self.verticalAxisOptionsGroupBox)
        self.valueRadioButton.setObjectName("valueRadioButton")
        self.gridLayout_10.addWidget(self.valueRadioButton, 3, 0, 1, 1)
        self.normaliseSliderButton = QtWidgets.QPushButton(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseSliderButton.sizePolicy().hasHeightForWidth())
        self.normaliseSliderButton.setSizePolicy(sizePolicy)
        self.normaliseSliderButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.normaliseSliderButton.setObjectName("normaliseSliderButton")
        self.gridLayout_10.addWidget(self.normaliseSliderButton, 2, 4, 1, 1)
        self.normaliseDateButton = QtWidgets.QPushButton(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseDateButton.sizePolicy().hasHeightForWidth())
        self.normaliseDateButton.setSizePolicy(sizePolicy)
        self.normaliseDateButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.normaliseDateButton.setObjectName("normaliseDateButton")
        self.gridLayout_10.addWidget(self.normaliseDateButton, 2, 2, 1, 1)
        self.autoNormaliseCheckBox = QtWidgets.QCheckBox(self.verticalAxisOptionsGroupBox)
        self.autoNormaliseCheckBox.setObjectName("autoNormaliseCheckBox")
        self.gridLayout_10.addWidget(self.autoNormaliseCheckBox, 2, 5, 1, 1)
        self.axisOptionsLayout.addWidget(self.verticalAxisOptionsGroupBox)
        self.horizontalAxisOptionsGroupBox = QtWidgets.QGroupBox(self.axisOptionsFrame)
        self.horizontalAxisOptionsGroupBox.setObjectName("horizontalAxisOptionsGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.horizontalAxisOptionsGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._3YPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._3YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3YPushButton.setObjectName("_3YPushButton")
        self.gridLayout_2.addWidget(self._3YPushButton, 2, 5, 1, 1)
        self._6MPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._6MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._6MPushButton.setObjectName("_6MPushButton")
        self.gridLayout_2.addWidget(self._6MPushButton, 2, 6, 1, 1)
        self._3MPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._3MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3MPushButton.setObjectName("_3MPushButton")
        self.gridLayout_2.addWidget(self._3MPushButton, 2, 4, 1, 1)
        self.maxPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self.maxPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxPushButton.setObjectName("maxPushButton")
        self.gridLayout_2.addWidget(self.maxPushButton, 2, 10, 1, 1)
        self._5YPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._5YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._5YPushButton.setObjectName("_5YPushButton")
        self.gridLayout_2.addWidget(self._5YPushButton, 2, 8, 1, 1)
        self._1YPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._1YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1YPushButton.setObjectName("_1YPushButton")
        self.gridLayout_2.addWidget(self._1YPushButton, 2, 7, 1, 1)
        self._10YPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._10YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._10YPushButton.setObjectName("_10YPushButton")
        self.gridLayout_2.addWidget(self._10YPushButton, 2, 9, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fromDateEdit = QtWidgets.QDateEdit(self.horizontalAxisOptionsGroupBox)
        self.fromDateEdit.setObjectName("fromDateEdit")
        self.horizontalLayout_2.addWidget(self.fromDateEdit)
        self.toLabel = QtWidgets.QLabel(self.horizontalAxisOptionsGroupBox)
        self.toLabel.setObjectName("toLabel")
        self.horizontalLayout_2.addWidget(self.toLabel)
        self.toDateEdit = QtWidgets.QDateEdit(self.horizontalAxisOptionsGroupBox)
        self.toDateEdit.setObjectName("toDateEdit")
        self.horizontalLayout_2.addWidget(self.toDateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 3, 1, 8)
        self._1MPushButton = QtWidgets.QPushButton(self.horizontalAxisOptionsGroupBox)
        self._1MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1MPushButton.setObjectName("_1MPushButton")
        self.gridLayout_2.addWidget(self._1MPushButton, 2, 3, 1, 1)
        self.axisOptionsLayout.addWidget(self.horizontalAxisOptionsGroupBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.axisOptionsLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.axisOptionsFrame)
        self.horizontalFrame = QtWidgets.QFrame(chartWidget)
        self.horizontalFrame.setLineWidth(0)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalFrame)
        self.groupBox.setObjectName("groupBox")
        self.graphLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.graphLayout.setObjectName("graphLayout")
        self.graphWidget = PlotWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setObjectName("graphWidget")
        self.graphLayout.addWidget(self.graphWidget)
        self.rangeWidget = PlotWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rangeWidget.sizePolicy().hasHeightForWidth())
        self.rangeWidget.setSizePolicy(sizePolicy)
        self.rangeWidget.setObjectName("rangeWidget")
        self.graphLayout.addWidget(self.rangeWidget)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.legendGroupBox = QtWidgets.QGroupBox(self.horizontalFrame)
        self.legendGroupBox.setObjectName("legendGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.legendGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.hideAllButton = QtWidgets.QPushButton(self.legendGroupBox)
        self.hideAllButton.setObjectName("hideAllButton")
        self.gridLayout_8.addWidget(self.hideAllButton, 0, 1, 1, 1)
        self.showAllButton = QtWidgets.QPushButton(self.legendGroupBox)
        self.showAllButton.setObjectName("showAllButton")
        self.gridLayout_8.addWidget(self.showAllButton, 0, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.legendGroupBox)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_8.addWidget(self.deleteButton, 2, 0, 1, 1)
        self.legend = QtWidgets.QTreeView(self.legendGroupBox)
        self.legend.setMinimumSize(QtCore.QSize(160, 0))
        self.legend.setMaximumSize(QtCore.QSize(160, 16777215))
        self.legend.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.legend.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.legend.setObjectName("legend")
        self.gridLayout_8.addWidget(self.legend, 1, 0, 1, 2)
        self.horizontalLayout_4.addWidget(self.legendGroupBox)
        self.verticalLayout.addWidget(self.horizontalFrame)

        self.retranslateUi(chartWidget)
        QtCore.QMetaObject.connectSlotsByName(chartWidget)
        chartWidget.setTabOrder(self.percentageRadioButton, self.valueRadioButton)
        chartWidget.setTabOrder(self.valueRadioButton, self.normaliseSliderButton)
        chartWidget.setTabOrder(self.normaliseSliderButton, self._3YPushButton)
        chartWidget.setTabOrder(self._3YPushButton, self._5YPushButton)
        chartWidget.setTabOrder(self._5YPushButton, self._10YPushButton)
        chartWidget.setTabOrder(self._10YPushButton, self.maxPushButton)
        chartWidget.setTabOrder(self.maxPushButton, self.showAllButton)
        chartWidget.setTabOrder(self.showAllButton, self.hideAllButton)
        chartWidget.setTabOrder(self.hideAllButton, self.legend)

    def retranslateUi(self, chartWidget):
        _translate = QtCore.QCoreApplication.translate
        chartWidget.setWindowTitle(_translate("chartWidget", "Form"))
        self.axisOptionsButton.setText(_translate("chartWidget", "Options"))
        self.legendButton.setText(_translate("chartWidget", "Legend"))
        self.verticalAxisOptionsGroupBox.setTitle(_translate("chartWidget", "Vertical Axis"))
        self.normaliseStartButton.setText(_translate("chartWidget", "Start"))
        self.percentageRadioButton.setText(_translate("chartWidget", "Percentage"))
        self.valueRadioButton.setText(_translate("chartWidget", "Value"))
        self.normaliseSliderButton.setText(_translate("chartWidget", "Slider"))
        self.normaliseDateButton.setText(_translate("chartWidget", "Date"))
        self.autoNormaliseCheckBox.setText(_translate("chartWidget", "Auto"))
        self.horizontalAxisOptionsGroupBox.setTitle(_translate("chartWidget", "Horizontal Axis"))
        self._3YPushButton.setText(_translate("chartWidget", "3Y"))
        self._6MPushButton.setText(_translate("chartWidget", "6M"))
        self._3MPushButton.setText(_translate("chartWidget", "3M"))
        self.maxPushButton.setText(_translate("chartWidget", "Max"))
        self._5YPushButton.setText(_translate("chartWidget", "5Y"))
        self._1YPushButton.setText(_translate("chartWidget", "1Y"))
        self._10YPushButton.setText(_translate("chartWidget", "10Y"))
        self.toLabel.setText(_translate("chartWidget", "to"))
        self._1MPushButton.setText(_translate("chartWidget", "1M"))
        self.hideAllButton.setText(_translate("chartWidget", "Hide All"))
        self.showAllButton.setText(_translate("chartWidget", "Show All"))
        self.deleteButton.setText(_translate("chartWidget", "Delete"))

from pyqtgraph import PlotWidget
