# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chartWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chartWidget(object):
    def setupUi(self, chartWidget):
        chartWidget.setObjectName("chartWidget")
        chartWidget.resize(800, 367)
        self.verticalLayout = QtWidgets.QVBoxLayout(chartWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(chartWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 0, 1, 1)
        self.legendCheckBox = QtWidgets.QCheckBox(chartWidget)
        self.legendCheckBox.setChecked(True)
        self.legendCheckBox.setObjectName("legendCheckBox")
        self.gridLayout_3.addWidget(self.legendCheckBox, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.graphWidget = PlotWidget(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout_5.addWidget(self.graphWidget, 0, 0, 1, 1)
        self.rangeWidget = PlotWidget(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rangeWidget.sizePolicy().hasHeightForWidth())
        self.rangeWidget.setSizePolicy(sizePolicy)
        self.rangeWidget.setObjectName("rangeWidget")
        self.gridLayout_5.addWidget(self.rangeWidget, 1, 0, 1, 1)
        self.legend = QtWidgets.QListView(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legend.sizePolicy().hasHeightForWidth())
        self.legend.setSizePolicy(sizePolicy)
        self.legend.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.legend.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.legend.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.legend.setObjectName("legend")
        self.gridLayout_5.addWidget(self.legend, 0, 1, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fromDateEdit = QtWidgets.QDateEdit(chartWidget)
        self.fromDateEdit.setObjectName("fromDateEdit")
        self.gridLayout_2.addWidget(self.fromDateEdit, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(chartWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 2, 1)
        self.toDateEdit = QtWidgets.QDateEdit(chartWidget)
        self.toDateEdit.setObjectName("toDateEdit")
        self.gridLayout_2.addWidget(self.toDateEdit, 0, 2, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 2, 1)
        self._1MPushButton = QtWidgets.QPushButton(chartWidget)
        self._1MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1MPushButton.setObjectName("_1MPushButton")
        self.gridLayout_2.addWidget(self._1MPushButton, 0, 4, 2, 1)
        self._3MPushButton = QtWidgets.QPushButton(chartWidget)
        self._3MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3MPushButton.setObjectName("_3MPushButton")
        self.gridLayout_2.addWidget(self._3MPushButton, 0, 5, 2, 1)
        self._6MPushButton = QtWidgets.QPushButton(chartWidget)
        self._6MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._6MPushButton.setObjectName("_6MPushButton")
        self.gridLayout_2.addWidget(self._6MPushButton, 0, 6, 2, 1)
        self._1YPushButton = QtWidgets.QPushButton(chartWidget)
        self._1YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1YPushButton.setObjectName("_1YPushButton")
        self.gridLayout_2.addWidget(self._1YPushButton, 0, 7, 2, 1)
        self._3YPushButton = QtWidgets.QPushButton(chartWidget)
        self._3YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3YPushButton.setObjectName("_3YPushButton")
        self.gridLayout_2.addWidget(self._3YPushButton, 0, 8, 2, 1)
        self._5YPushButton = QtWidgets.QPushButton(chartWidget)
        self._5YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._5YPushButton.setObjectName("_5YPushButton")
        self.gridLayout_2.addWidget(self._5YPushButton, 0, 9, 2, 1)
        self._10YPushButton = QtWidgets.QPushButton(chartWidget)
        self._10YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._10YPushButton.setObjectName("_10YPushButton")
        self.gridLayout_2.addWidget(self._10YPushButton, 0, 10, 2, 1)
        self.maxPushButton = QtWidgets.QPushButton(chartWidget)
        self.maxPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxPushButton.setObjectName("maxPushButton")
        self.gridLayout_2.addWidget(self.maxPushButton, 0, 11, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(chartWidget)
        QtCore.QMetaObject.connectSlotsByName(chartWidget)

    def retranslateUi(self, chartWidget):
        _translate = QtCore.QCoreApplication.translate
        chartWidget.setWindowTitle(_translate("chartWidget", "Form"))
        self.comboBox.setItemText(0, _translate("chartWidget", "Perentage"))
        self.comboBox.setItemText(1, _translate("chartWidget", "Value"))
        self.legendCheckBox.setText(_translate("chartWidget", "Legend"))
        self.label.setText(_translate("chartWidget", "to"))
        self._1MPushButton.setText(_translate("chartWidget", "1M"))
        self._3MPushButton.setText(_translate("chartWidget", "3M"))
        self._6MPushButton.setText(_translate("chartWidget", "6M"))
        self._1YPushButton.setText(_translate("chartWidget", "1Y"))
        self._3YPushButton.setText(_translate("chartWidget", "3Y"))
        self._5YPushButton.setText(_translate("chartWidget", "5Y"))
        self._10YPushButton.setText(_translate("chartWidget", "10Y"))
        self.maxPushButton.setText(_translate("chartWidget", "Max"))
from pyqtgraph import PlotWidget
