# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chartWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chartWidget(object):
    def setupUi(self, chartWidget):
        chartWidget.setObjectName("chartWidget")
        chartWidget.resize(800, 506)
        self.gridLayout_3 = QtWidgets.QGridLayout(chartWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.legendGroupBox = QtWidgets.QGroupBox(chartWidget)
        self.legendGroupBox.setObjectName("legendGroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.legendGroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.hideAllButton = QtWidgets.QPushButton(self.legendGroupBox)
        self.hideAllButton.setObjectName("hideAllButton")
        self.gridLayout_8.addWidget(self.hideAllButton, 0, 1, 1, 1)
        self.legend = QtWidgets.QListView(self.legendGroupBox)
        self.legend.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.legend.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.legend.setObjectName("legend")
        self.gridLayout_8.addWidget(self.legend, 1, 0, 1, 2)
        self.showAllButton = QtWidgets.QPushButton(self.legendGroupBox)
        self.showAllButton.setObjectName("showAllButton")
        self.gridLayout_8.addWidget(self.showAllButton, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.legendGroupBox, 3, 2, 5, 1)
        self.rangeWidget = PlotWidget(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rangeWidget.sizePolicy().hasHeightForWidth())
        self.rangeWidget.setSizePolicy(sizePolicy)
        self.rangeWidget.setObjectName("rangeWidget")
        self.gridLayout_3.addWidget(self.rangeWidget, 6, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 2)
        self.verticalAxisOptionsGroupBox = QtWidgets.QGroupBox(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalAxisOptionsGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalAxisOptionsGroupBox.setSizePolicy(sizePolicy)
        self.verticalAxisOptionsGroupBox.setObjectName("verticalAxisOptionsGroupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.verticalAxisOptionsGroupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.normaliseDateButton = QtWidgets.QPushButton(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseDateButton.sizePolicy().hasHeightForWidth())
        self.normaliseDateButton.setSizePolicy(sizePolicy)
        self.normaliseDateButton.setObjectName("normaliseDateButton")
        self.gridLayout_10.addWidget(self.normaliseDateButton, 2, 3, 1, 1)
        self.normaliseDateEdit = QtWidgets.QDateEdit(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseDateEdit.sizePolicy().hasHeightForWidth())
        self.normaliseDateEdit.setSizePolicy(sizePolicy)
        self.normaliseDateEdit.setObjectName("normaliseDateEdit")
        self.gridLayout_10.addWidget(self.normaliseDateEdit, 2, 4, 1, 1)
        self.normaliseSliderButton = QtWidgets.QPushButton(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normaliseSliderButton.sizePolicy().hasHeightForWidth())
        self.normaliseSliderButton.setSizePolicy(sizePolicy)
        self.normaliseSliderButton.setObjectName("normaliseSliderButton")
        self.gridLayout_10.addWidget(self.normaliseSliderButton, 2, 1, 1, 1)
        self.y_axisScaleComboBox = QtWidgets.QComboBox(self.verticalAxisOptionsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_axisScaleComboBox.sizePolicy().hasHeightForWidth())
        self.y_axisScaleComboBox.setSizePolicy(sizePolicy)
        self.y_axisScaleComboBox.setMinimumSize(QtCore.QSize(93, 0))
        self.y_axisScaleComboBox.setMaximumSize(QtCore.QSize(93, 16777215))
        self.y_axisScaleComboBox.setObjectName("y_axisScaleComboBox")
        self.y_axisScaleComboBox.addItem("")
        self.y_axisScaleComboBox.addItem("")
        self.gridLayout_10.addWidget(self.y_axisScaleComboBox, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.verticalAxisOptionsGroupBox, 0, 0, 2, 1)
        self.legendButton = QtWidgets.QToolButton(chartWidget)
        self.legendButton.setCheckable(True)
        self.legendButton.setChecked(True)
        self.legendButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.legendButton.setArrowType(QtCore.Qt.UpArrow)
        self.legendButton.setObjectName("legendButton")
        self.gridLayout.addWidget(self.legendButton, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 3)
        self.graphWidget = PlotWidget(chartWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setObjectName("graphWidget")
        self.gridLayout_3.addWidget(self.graphWidget, 5, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(chartWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._1MPushButton = QtWidgets.QPushButton(self.groupBox)
        self._1MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1MPushButton.setObjectName("_1MPushButton")
        self.gridLayout_2.addWidget(self._1MPushButton, 0, 4, 2, 1)
        self._3YPushButton = QtWidgets.QPushButton(self.groupBox)
        self._3YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3YPushButton.setObjectName("_3YPushButton")
        self.gridLayout_2.addWidget(self._3YPushButton, 0, 8, 2, 1)
        self.maxPushButton = QtWidgets.QPushButton(self.groupBox)
        self.maxPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxPushButton.setObjectName("maxPushButton")
        self.gridLayout_2.addWidget(self.maxPushButton, 0, 11, 2, 1)
        self._5YPushButton = QtWidgets.QPushButton(self.groupBox)
        self._5YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._5YPushButton.setObjectName("_5YPushButton")
        self.gridLayout_2.addWidget(self._5YPushButton, 0, 9, 2, 1)
        self._6MPushButton = QtWidgets.QPushButton(self.groupBox)
        self._6MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._6MPushButton.setObjectName("_6MPushButton")
        self.gridLayout_2.addWidget(self._6MPushButton, 0, 6, 2, 1)
        self.toDateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.toDateEdit.setObjectName("toDateEdit")
        self.gridLayout_2.addWidget(self.toDateEdit, 0, 2, 2, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 2, 1)
        self._3MPushButton = QtWidgets.QPushButton(self.groupBox)
        self._3MPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._3MPushButton.setObjectName("_3MPushButton")
        self.gridLayout_2.addWidget(self._3MPushButton, 0, 5, 2, 1)
        self.fromDateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.fromDateEdit.setObjectName("fromDateEdit")
        self.gridLayout_2.addWidget(self.fromDateEdit, 0, 0, 2, 1)
        self._1YPushButton = QtWidgets.QPushButton(self.groupBox)
        self._1YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._1YPushButton.setObjectName("_1YPushButton")
        self.gridLayout_2.addWidget(self._1YPushButton, 0, 7, 2, 1)
        self._10YPushButton = QtWidgets.QPushButton(self.groupBox)
        self._10YPushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self._10YPushButton.setObjectName("_10YPushButton")
        self.gridLayout_2.addWidget(self._10YPushButton, 0, 10, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 2, 1)
        self.gridLayout_3.addWidget(self.groupBox, 7, 0, 1, 2)

        self.retranslateUi(chartWidget)
        QtCore.QMetaObject.connectSlotsByName(chartWidget)

    def retranslateUi(self, chartWidget):
        _translate = QtCore.QCoreApplication.translate
        chartWidget.setWindowTitle(_translate("chartWidget", "Form"))
        self.hideAllButton.setText(_translate("chartWidget", "Hide All"))
        self.showAllButton.setText(_translate("chartWidget", "Show All"))
        self.verticalAxisOptionsGroupBox.setTitle(_translate("chartWidget", "Vertical Axis"))
        self.normaliseDateButton.setText(_translate("chartWidget", "Normalise to date"))
        self.normaliseSliderButton.setText(_translate("chartWidget", "Normalise to slider"))
        self.y_axisScaleComboBox.setItemText(0, _translate("chartWidget", "Percentage"))
        self.y_axisScaleComboBox.setItemText(1, _translate("chartWidget", "Value"))
        self.legendButton.setText(_translate("chartWidget", "Legend"))
        self.groupBox.setTitle(_translate("chartWidget", "Horizontal Axis"))
        self._1MPushButton.setText(_translate("chartWidget", "1M"))
        self._3YPushButton.setText(_translate("chartWidget", "3Y"))
        self.maxPushButton.setText(_translate("chartWidget", "Max"))
        self._5YPushButton.setText(_translate("chartWidget", "5Y"))
        self._6MPushButton.setText(_translate("chartWidget", "6M"))
        self.label.setText(_translate("chartWidget", "to"))
        self._3MPushButton.setText(_translate("chartWidget", "3M"))
        self._1YPushButton.setText(_translate("chartWidget", "1Y"))
        self._10YPushButton.setText(_translate("chartWidget", "10Y"))
from pyqtgraph import PlotWidget
