# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equityWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_equityWidget(object):
    def setupUi(self, equityWidget):
        equityWidget.setObjectName("equityWidget")
        equityWidget.resize(270, 421)
        equityWidget.setMinimumSize(QtCore.QSize(270, 0))
        self.gridLayout_2 = QtWidgets.QGridLayout(equityWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name = QtWidgets.QLineEdit(equityWidget)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 3)
        self.providerCodeLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.providerCodeLineEdit.setReadOnly(True)
        self.providerCodeLineEdit.setObjectName("providerCodeLineEdit")
        self.gridLayout_2.addWidget(self.providerCodeLineEdit, 9, 1, 1, 3)
        self.equityFileButton = QtWidgets.QToolButton(equityWidget)
        self.equityFileButton.setObjectName("equityFileButton")
        self.gridLayout_2.addWidget(self.equityFileButton, 3, 3, 1, 1)
        self.dataFileLabel = QtWidgets.QLabel(equityWidget)
        self.dataFileLabel.setObjectName("dataFileLabel")
        self.gridLayout_2.addWidget(self.dataFileLabel, 15, 0, 1, 1)
        self.saved_data_start_date = QtWidgets.QDateEdit(equityWidget)
        self.saved_data_start_date.setReadOnly(True)
        self.saved_data_start_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.saved_data_start_date.setObjectName("saved_data_start_date")
        self.gridLayout_2.addWidget(self.saved_data_start_date, 17, 1, 1, 1)
        self.dataFileLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.dataFileLineEdit.setReadOnly(True)
        self.dataFileLineEdit.setObjectName("dataFileLineEdit")
        self.gridLayout_2.addWidget(self.dataFileLineEdit, 15, 1, 1, 2)
        self.providerCodeLabel = QtWidgets.QLabel(equityWidget)
        self.providerCodeLabel.setObjectName("providerCodeLabel")
        self.gridLayout_2.addWidget(self.providerCodeLabel, 9, 0, 1, 1)
        self.universeLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.universeLineEdit.setObjectName("universeLineEdit")
        self.gridLayout_2.addWidget(self.universeLineEdit, 8, 1, 1, 3)
        self.dataStartLabel = QtWidgets.QLabel(equityWidget)
        self.dataStartLabel.setEnabled(True)
        self.dataStartLabel.setObjectName("dataStartLabel")
        self.gridLayout_2.addWidget(self.dataStartLabel, 17, 0, 1, 1)
        self.dataEndLabel = QtWidgets.QLabel(equityWidget)
        self.dataEndLabel.setObjectName("dataEndLabel")
        self.gridLayout_2.addWidget(self.dataEndLabel, 18, 0, 1, 1)
        self.ISIN = QtWidgets.QLineEdit(equityWidget)
        self.ISIN.setReadOnly(True)
        self.ISIN.setObjectName("ISIN")
        self.gridLayout_2.addWidget(self.ISIN, 1, 1, 1, 3)
        self.urlButton = QtWidgets.QToolButton(equityWidget)
        self.urlButton.setObjectName("urlButton")
        self.gridLayout_2.addWidget(self.urlButton, 10, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(equityWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.providerLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.providerLineEdit.setReadOnly(True)
        self.providerLineEdit.setObjectName("providerLineEdit")
        self.gridLayout_2.addWidget(self.providerLineEdit, 6, 1, 1, 3)
        self.line = QtWidgets.QFrame(equityWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 14, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(equityWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.secIdLabel = QtWidgets.QLabel(equityWidget)
        self.secIdLabel.setObjectName("secIdLabel")
        self.gridLayout_2.addWidget(self.secIdLabel, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(equityWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.symbol = QtWidgets.QLineEdit(equityWidget)
        self.symbol.setMaximumSize(QtCore.QSize(40, 16777215))
        self.symbol.setReadOnly(True)
        self.symbol.setObjectName("symbol")
        self.gridLayout_2.addWidget(self.symbol, 5, 1, 1, 1)
        self.providerLabel = QtWidgets.QLabel(equityWidget)
        self.providerLabel.setObjectName("providerLabel")
        self.gridLayout_2.addWidget(self.providerLabel, 6, 0, 1, 1)
        self.saved_data_end_date = QtWidgets.QDateEdit(equityWidget)
        self.saved_data_end_date.setReadOnly(True)
        self.saved_data_end_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.saved_data_end_date.setObjectName("saved_data_end_date")
        self.gridLayout_2.addWidget(self.saved_data_end_date, 18, 1, 1, 1)
        self.unit = QtWidgets.QLineEdit(equityWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit.sizePolicy().hasHeightForWidth())
        self.unit.setSizePolicy(sizePolicy)
        self.unit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.unit.setBaseSize(QtCore.QSize(40, 0))
        self.unit.setReadOnly(True)
        self.unit.setObjectName("unit")
        self.gridLayout_2.addWidget(self.unit, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chartButton = QtWidgets.QToolButton(equityWidget)
        self.chartButton.setCheckable(True)
        self.chartButton.setChecked(False)
        self.chartButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.chartButton.setArrowType(QtCore.Qt.RightArrow)
        self.chartButton.setObjectName("chartButton")
        self.horizontalLayout.addWidget(self.chartButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 19, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(equityWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(equityWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.urlLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.gridLayout_2.addWidget(self.urlLineEdit, 10, 1, 1, 2)
        self.type = QtWidgets.QLineEdit(equityWidget)
        self.type.setReadOnly(True)
        self.type.setObjectName("type")
        self.gridLayout_2.addWidget(self.type, 2, 1, 1, 3)
        self.dataFileButton = QtWidgets.QToolButton(equityWidget)
        self.dataFileButton.setObjectName("dataFileButton")
        self.gridLayout_2.addWidget(self.dataFileButton, 15, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(equityWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.urlLabel = QtWidgets.QLabel(equityWidget)
        self.urlLabel.setObjectName("urlLabel")
        self.gridLayout_2.addWidget(self.urlLabel, 10, 0, 1, 1)
        self.secIdLineEdit = QtWidgets.QLineEdit(equityWidget)
        self.secIdLineEdit.setObjectName("secIdLineEdit")
        self.gridLayout_2.addWidget(self.secIdLineEdit, 7, 1, 1, 3)
        self.equity_file = QtWidgets.QLineEdit(equityWidget)
        self.equity_file.setReadOnly(True)
        self.equity_file.setObjectName("equity_file")
        self.gridLayout_2.addWidget(self.equity_file, 3, 1, 1, 2)
        self.universeLabel = QtWidgets.QLabel(equityWidget)
        self.universeLabel.setObjectName("universeLabel")
        self.gridLayout_2.addWidget(self.universeLabel, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 20, 0, 1, 4)

        self.retranslateUi(equityWidget)
        QtCore.QMetaObject.connectSlotsByName(equityWidget)

    def retranslateUi(self, equityWidget):
        _translate = QtCore.QCoreApplication.translate
        equityWidget.setWindowTitle(_translate("equityWidget", "Form"))
        self.equityFileButton.setText(_translate("equityWidget", "..."))
        self.dataFileLabel.setText(_translate("equityWidget", "Data file"))
        self.providerCodeLabel.setText(_translate("equityWidget", "Provider code (id)"))
        self.dataStartLabel.setText(_translate("equityWidget", "Saved data start"))
        self.dataEndLabel.setText(_translate("equityWidget", "Saved data end"))
        self.urlButton.setText(_translate("equityWidget", "..."))
        self.label_6.setText(_translate("equityWidget", "Equity file"))
        self.label_5.setText(_translate("equityWidget", "Symbol"))
        self.secIdLabel.setText(_translate("equityWidget", "secId"))
        self.label_3.setText(_translate("equityWidget", "Equity type"))
        self.providerLabel.setText(_translate("equityWidget", "Data provider"))
        self.chartButton.setText(_translate("equityWidget", "Pop out chart"))
        self.label_2.setText(_translate("equityWidget", "ISIN"))
        self.label.setText(_translate("equityWidget", "Name"))
        self.dataFileButton.setText(_translate("equityWidget", "..."))
        self.label_4.setText(_translate("equityWidget", "Unit"))
        self.urlLabel.setText(_translate("equityWidget", "URL"))
        self.universeLabel.setText(_translate("equityWidget", "universe"))

