# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sellprice.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 402)
        MainWindow.setMaximumSize(QtCore.QSize(252, 402))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.QuantityEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.QuantityEdit.setObjectName("QuantityEdit")
        self.gridLayout.addWidget(self.QuantityEdit, 1, 2, 1, 1)
        self.StampDutyEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StampDutyEdit.setObjectName("StampDutyEdit")
        self.gridLayout.addWidget(self.StampDutyEdit, 2, 2, 2, 1)
        self.StampDutyCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.StampDutyCheckBox.setChecked(True)
        self.StampDutyCheckBox.setObjectName("StampDutyCheckBox")
        self.gridLayout.addWidget(self.StampDutyCheckBox, 2, 1, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 2, 2)
        self.CommissionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CommissionEdit.setObjectName("CommissionEdit")
        self.gridLayout.addWidget(self.CommissionEdit, 4, 2, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.BuyUnitsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.BuyUnitsComboBox.setObjectName("BuyUnitsComboBox")
        self.BuyUnitsComboBox.addItem("")
        self.BuyUnitsComboBox.addItem("")
        self.gridLayout.addWidget(self.BuyUnitsComboBox, 0, 3, 1, 2)
        self.BuyDue = QtWidgets.QLineEdit(self.centralwidget)
        self.BuyDue.setEnabled(False)
        self.BuyDue.setObjectName("BuyDue")
        self.gridLayout.addWidget(self.BuyDue, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 3, 1, 2)
        self.BuyPriceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.BuyPriceEdit.setText("")
        self.BuyPriceEdit.setObjectName("BuyPriceEdit")
        self.gridLayout.addWidget(self.BuyPriceEdit, 0, 2, 1, 1)
        self.CommissionCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.CommissionCheckBox.setChecked(True)
        self.CommissionCheckBox.setObjectName("CommissionCheckBox")
        self.gridLayout.addWidget(self.CommissionCheckBox, 4, 1, 3, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 1, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 3, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 9, 1, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)
        self.resultslayout = QtWidgets.QGridLayout()
        self.resultslayout.setObjectName("resultslayout")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.resultslayout.addWidget(self.label_15, 3, 1, 1, 1)
        self.pos_25_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_25_price.setEnabled(False)
        self.pos_25_price.setObjectName("pos_25_price")
        self.resultslayout.addWidget(self.pos_25_price, 7, 3, 1, 1)
        self.SellPriceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SellPriceEdit.setEnabled(False)
        self.SellPriceEdit.setObjectName("SellPriceEdit")
        self.resultslayout.addWidget(self.SellPriceEdit, 10, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.resultslayout.addWidget(self.label_19, 7, 1, 1, 1)
        self.ProfitEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ProfitEdit.setEnabled(False)
        self.ProfitEdit.setObjectName("ProfitEdit")
        self.resultslayout.addWidget(self.ProfitEdit, 10, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.resultslayout.addWidget(self.label_17, 5, 1, 1, 1)
        self.pos_5_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_5_price.setEnabled(False)
        self.pos_5_price.setObjectName("pos_5_price")
        self.resultslayout.addWidget(self.pos_5_price, 3, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.resultslayout.addWidget(self.label_18, 6, 1, 1, 1)
        self.pos_5_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_5_profit.setEnabled(False)
        self.pos_5_profit.setObjectName("pos_5_profit")
        self.resultslayout.addWidget(self.pos_5_profit, 3, 2, 1, 1)
        self.pos_25_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_25_profit.setEnabled(False)
        self.pos_25_profit.setObjectName("pos_25_profit")
        self.resultslayout.addWidget(self.pos_25_profit, 7, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.resultslayout.addWidget(self.line_2, 8, 1, 1, 3)
        self.pos_0_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_0_profit.setEnabled(False)
        self.pos_0_profit.setObjectName("pos_0_profit")
        self.resultslayout.addWidget(self.pos_0_profit, 2, 2, 1, 1)
        self.pos_20_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_20_price.setEnabled(False)
        self.pos_20_price.setObjectName("pos_20_price")
        self.resultslayout.addWidget(self.pos_20_price, 6, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.SellUnitsComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SellUnitsComboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SellUnitsComboBox.setObjectName("SellUnitsComboBox")
        self.SellUnitsComboBox.addItem("")
        self.SellUnitsComboBox.addItem("")
        self.horizontalLayout.addWidget(self.SellUnitsComboBox)
        self.resultslayout.addLayout(self.horizontalLayout, 0, 3, 2, 1)
        self.pos_10_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_10_profit.setEnabled(False)
        self.pos_10_profit.setObjectName("pos_10_profit")
        self.resultslayout.addWidget(self.pos_10_profit, 4, 2, 1, 1)
        self.ProfitPercentageEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ProfitPercentageEdit.setObjectName("ProfitPercentageEdit")
        self.resultslayout.addWidget(self.ProfitPercentageEdit, 10, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.resultslayout.addWidget(self.label_8, 0, 1, 2, 1)
        self.pos_15_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_15_profit.setEnabled(False)
        self.pos_15_profit.setObjectName("pos_15_profit")
        self.resultslayout.addWidget(self.pos_15_profit, 5, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.resultslayout.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(74, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.resultslayout.addWidget(self.label_9, 0, 2, 2, 1)
        self.pos_15_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_15_price.setEnabled(False)
        self.pos_15_price.setObjectName("pos_15_price")
        self.resultslayout.addWidget(self.pos_15_price, 5, 3, 1, 1)
        self.pos_0_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_0_price.setEnabled(False)
        self.pos_0_price.setObjectName("pos_0_price")
        self.resultslayout.addWidget(self.pos_0_price, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.resultslayout.addWidget(self.label_16, 4, 1, 1, 1)
        self.pos_20_profit = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_20_profit.setEnabled(False)
        self.pos_20_profit.setObjectName("pos_20_profit")
        self.resultslayout.addWidget(self.pos_20_profit, 6, 2, 1, 1)
        self.pos_10_price = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_10_price.setEnabled(False)
        self.pos_10_price.setObjectName("pos_10_price")
        self.resultslayout.addWidget(self.pos_10_price, 4, 3, 1, 1)
        self.ProfitPercentageRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ProfitPercentageRadioButton.setText("")
        self.ProfitPercentageRadioButton.setChecked(True)
        self.ProfitPercentageRadioButton.setObjectName("ProfitPercentageRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.ProfitPercentageRadioButton)
        self.resultslayout.addWidget(self.ProfitPercentageRadioButton, 9, 1, 1, 1)
        self.ProfitRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ProfitRadioButton.setText("")
        self.ProfitRadioButton.setObjectName("ProfitRadioButton")
        self.buttonGroup.addButton(self.ProfitRadioButton)
        self.resultslayout.addWidget(self.ProfitRadioButton, 9, 2, 1, 1)
        self.SellPriceRadioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.SellPriceRadioButton.setText("")
        self.SellPriceRadioButton.setObjectName("SellPriceRadioButton")
        self.buttonGroup.addButton(self.SellPriceRadioButton)
        self.resultslayout.addWidget(self.SellPriceRadioButton, 9, 3, 1, 1)
        self.verticalLayout.addLayout(self.resultslayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.StampDutyCheckBox.clicked['bool'].connect(self.StampDutyEdit.setEnabled)
        self.CommissionCheckBox.clicked['bool'].connect(self.CommissionEdit.setEnabled)
        self.BuyPriceEdit.returnPressed.connect(self.QuantityEdit.setFocus)
        self.StampDutyEdit.returnPressed.connect(self.CommissionEdit.setFocus)
        self.ProfitPercentageRadioButton.toggled['bool'].connect(self.ProfitPercentageEdit.setEnabled)
        self.ProfitPercentageRadioButton.toggled['bool'].connect(self.ProfitEdit.setDisabled)
        self.ProfitPercentageRadioButton.toggled['bool'].connect(self.SellPriceEdit.setDisabled)
        self.ProfitRadioButton.toggled['bool'].connect(self.ProfitPercentageEdit.setDisabled)
        self.ProfitRadioButton.toggled['bool'].connect(self.ProfitEdit.setEnabled)
        self.ProfitRadioButton.toggled['bool'].connect(self.SellPriceEdit.setDisabled)
        self.SellPriceRadioButton.toggled['bool'].connect(self.ProfitPercentageEdit.setDisabled)
        self.SellPriceRadioButton.toggled['bool'].connect(self.ProfitEdit.setDisabled)
        self.SellPriceRadioButton.toggled['bool'].connect(self.SellPriceEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.BuyPriceEdit, self.BuyUnitsComboBox)
        MainWindow.setTabOrder(self.BuyUnitsComboBox, self.QuantityEdit)
        MainWindow.setTabOrder(self.QuantityEdit, self.StampDutyCheckBox)
        MainWindow.setTabOrder(self.StampDutyCheckBox, self.StampDutyEdit)
        MainWindow.setTabOrder(self.StampDutyEdit, self.CommissionCheckBox)
        MainWindow.setTabOrder(self.CommissionCheckBox, self.CommissionEdit)
        MainWindow.setTabOrder(self.CommissionEdit, self.pos_25_price)
        MainWindow.setTabOrder(self.pos_25_price, self.pos_10_price)
        MainWindow.setTabOrder(self.pos_10_price, self.pos_15_price)
        MainWindow.setTabOrder(self.pos_15_price, self.pos_20_price)
        MainWindow.setTabOrder(self.pos_20_price, self.pos_0_price)
        MainWindow.setTabOrder(self.pos_0_price, self.pos_5_price)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sell price calculator"))
        self.StampDutyCheckBox.setText(_translate("MainWindow", "Stamp duty"))
        self.label_4.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "Quantity"))
        self.BuyUnitsComboBox.setCurrentText(_translate("MainWindow", "GBP"))
        self.BuyUnitsComboBox.setItemText(0, _translate("MainWindow", "GBP"))
        self.BuyUnitsComboBox.setItemText(1, _translate("MainWindow", "GBp"))
        self.label_3.setText(_translate("MainWindow", "Buy due"))
        self.label.setText(_translate("MainWindow", "Buy price"))
        self.label_5.setText(_translate("MainWindow", "GBP"))
        self.CommissionCheckBox.setText(_translate("MainWindow", "Commission"))
        self.label_6.setText(_translate("MainWindow", "GBP"))
        self.label_15.setText(_translate("MainWindow", "5%"))
        self.label_19.setText(_translate("MainWindow", "25%"))
        self.label_17.setText(_translate("MainWindow", "15%"))
        self.label_18.setText(_translate("MainWindow", "20%"))
        self.label_21.setText(_translate("MainWindow", "Sell price"))
        self.SellUnitsComboBox.setItemText(0, _translate("MainWindow", "GBP"))
        self.SellUnitsComboBox.setItemText(1, _translate("MainWindow", "GBp"))
        self.label_8.setText(_translate("MainWindow", "Profit %"))
        self.label_14.setText(_translate("MainWindow", "0%"))
        self.label_9.setText(_translate("MainWindow", "Profit GBP"))
        self.label_16.setText(_translate("MainWindow", "10%"))

